title: Magdalena RojasW
logo: "/assets/images/CvMagdalenaPhoto3.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Project Designer | Data Sc. under training | Python, SQL, BI| UX 
  <br><br>
  Lic. Pontificia Universidad Catolica de Chile | Business Statistics and Analysis Specialization, Rice University | Google Data Analytics Professional Certificate
  <br><br>
  <a href="https://www.linkedin.com/in/magdalena-rojas-w/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
