title: Magdalena Rojas W
logo: assets/img/magdalena_rojasw.jpg
description: Project Designer | BI Data Analyst in training | Python, SQL, Data Visualization, Tableau | UX
show_downloads: true
theme: jekyll-theme-minimal
[View my Linkedin](www.linkedin.com/in/magdalena-rojas-w)
