title: Magdalena RojasW
logo: "/assets/images/magdalena_rojasw.jpg?raw=true" # your photo (or logo) here
description: >-
  Project Designer | BI Data Analyst in training | Python, SQL, Data Visualization, Tableau | UX
  
  Project Design, Pontificia Universidad Catolica de Chile
  Business Statistics and Analysis Specialization, Rice University
  Google Data Analytics Professional Certificate
  
  <a href="https://www.linkedin.com/in/magdalena-rojas-w/">View My LinkedIn</a>
theme: jekyll-theme-minimal
